name: ${project.name}
id: ${artifactId}
version: ${project.version}
author: ${author}
main: ${groupId}.${artifactId}.${name}
commands:
  ${artifactId}:
    description: The main command for ${name}.
    aliases: []